name: Deploy Jekyll with GitHub Pages dependencies preinstalled
on:
  push:
    branches:
      - docs
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: npm install && npm run docs:build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          folder: docs/.vitepress/dist
          branch: static
